config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "tasks", to: "tasks#index"

  # get "tasks/new", to: "tasks#new"
  # post "tasks", to: "tasks#create"

  # get "tasks/:id", to: "tasks#show"

  # get "tasks/:id/edit", to: "tasks#edit"
  # patch "tasks/:id" to: "tasks#update"

  # delete "tasks/:id", to: "tasks#destroy"

  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Task#create</h1>

app/views/tasks/destroy.html.erb
<h1>Task#destroy</h1>
<p>Find me in app/views/task/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Task#edit</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div class="container text-center">
  <h1>Tasks</h1>
  <a href="http://localhost:3000/tasks/new" class="btn btn-primary">New Task</a>

  <div class="row text-center">
    <% @tasks.each do |task| %>
    <div class="col-xs-12 columns text-center">
      <%= link_to task.name, task_path(task) %>
    </div>
    <% end %>
  </div>

</div>

app/views/tasks/new.html.erb
<h1>Task#new</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<p><%= @task.description %></p>
<a href="../tasks/<%= @task.id %>" data-method="DELETE" class="btn btn-danger">Delete</a>

app/views/tasks/update.html.erb
<h1>Task#update</h1>
<p>Find me in app/views/task/update.html.erb</p>